export const carouselMockData = [
    {
        id: "spring-sale",
        title: "Spring Sale",
        subtitle: "Shop up to 70% off",
        badge: "MARKETPLACE",
        image: "/src/assets/carousel-images/spring.png",
        link: "/marketplace/featured",
    },
    {
        id: "scheduled-projects",
        title: "Scheduled Projects",
        subtitle: "Development Update",
        badge: "NEWS",
        image: "/src/assets/carousel-images/scheduled.png",
        link: "https://magazine.artstation.com/2025/03/scheduled-projects/",
    },
    {
        id: "trending-projects",
        title: "Trending Projects",
        subtitle: "Discover the Art of Assassin's Creed Shadows",
        badge: "ART BLAST",
        image: "/src/assets/carousel-images/trending.png",
        link: "https://magazine.artstation.com/2025/03/ubisoft-assassins-creed-shadows-art-blast/",
    },

    {
        id: "news",
        title: "Scheduled Projects",
        subtitle: "Development Update",
        badge: "NEWS",
        image: "/src/assets/carousel-images/news.png",
        link: "https://magazine.artstation.com/2025/03/scheduled-projects/",
    },
    {
        id: "artblast",
        title: "Ubisoft Assassin's Creed Shadows Art Blast",
        subtitle: "Discover the Art of Assassin's Creed Shadows",
        badge: "ART BLAST",
        image: "https://cdnb.artstation.com/p/top_row_items/images/000/002/709/20250327120422/original/ac-artblast-magazinearticle-1280x720-notext.jpg?1743095062",
        link: "https://magazine.artstation.com/2025/03/ubisoft-assassins-creed-shadows-art-blast/",
    },
    {
        id: "marketplace",
        title: "Spring Sale",
        subtitle: "Shop up to 70% off",
        badge: "MARKETPLACE",
        image: "https://cdna.artstation.com/p/top_row_items/images/000/002/710/20250328093732/original/artstation-marketplace-spring-sale-toprow-890x500.png?1743172652",
        link: "https://www.artstation.com/marketplace",
    },
    {
        id: "marketplace",
        title: "Spring Sale",
        subtitle: "Shop up to 70% off",
        badge: "MARKETPLACE",
        image: "https://cdna.artstation.com/p/top_row_items/images/000/002/710/20250328093732/original/artstation-marketplace-spring-sale-toprow-890x500.png?1743172652",
        link: "https://www.artstation.com/marketplace",
    },
    {
        id: "news",
        title: "Scheduled Projects",
        subtitle: "Development Update",
        badge: "NEWS",
        image: "https://cdnb.artstation.com/p/top_row_items/images/000/002/711/20250328132708/original/magazine-cover-1920x1080-pd.jpg?1743186428",
        link: "https://magazine.artstation.com/2025/03/scheduled-projects/",
    },
    {
        id: "artblast",
        title: "Ubisoft Assassin's Creed Shadows Art Blast",
        subtitle: "Discover the Art of Assassin's Creed Shadows",
        badge: "ART BLAST",
        image: "https://cdnb.artstation.com/p/top_row_items/images/000/002/709/20250327120422/original/ac-artblast-magazinearticle-1280x720-notext.jpg?1743095062",
        link: "https://magazine.artstation.com/2025/03/ubisoft-assassins-creed-shadows-art-blast/",
    },
    {
        id: "news",
        title: "Scheduled Projects",
        subtitle: "Development Update",
        badge: "NEWS",
        image: "https://cdnb.artstation.com/p/top_row_items/images/000/002/711/20250328132708/original/magazine-cover-1920x1080-pd.jpg?1743186428",
        link: "https://magazine.artstation.com/2025/03/scheduled-projects/",
    },
    {
        id: "marketplace",
        title: "Spring Sale",
        subtitle: "Shop up to 70% off",
        badge: "MARKETPLACE",
        image: "https://cdna.artstation.com/p/top_row_items/images/000/002/710/20250328093732/original/artstation-marketplace-spring-sale-toprow-890x500.png?1743172652",
        link: "https://www.artstation.com/marketplace",
    },
    {
        id: "news",
        title: "Scheduled Projects",
        subtitle: "Development Update",
        badge: "NEWS",
        image: "https://cdnb.artstation.com/p/top_row_items/images/000/002/711/20250328132708/original/magazine-cover-1920x1080-pd.jpg?1743186428",
        link: "https://magazine.artstation.com/2025/03/scheduled-projects/",
    },
];