import { STATIC_ASSETS } from "../../config/assetsConfig";

export const featuredMockData = [
    {
        id: "spring-sale",
        title: "Spring Sale",
        subtitle: "Shop up to 70% off",
        badge: "MARKETPLACE",
        image: STATIC_ASSETS.CAROUSEL.SPRING_SALE,
        link: "/marketplace/featured",
    },
    {
        id: "scheduled-projects",
        title: "Scheduled Projects",
        subtitle: "Development Update",
        badge: "NEWS",
        image: STATIC_ASSETS.CAROUSEL.SCHEDULED_PROJECTS,
        link: "magazine/new-arrivals",
    },
    {
        id: "trending-projects",
        title: "Trending Projects",
        subtitle: "Discover the Art of Assassin's Creed Shadows",
        badge: "ART BLAST",
        image: STATIC_ASSETS.CAROUSEL.TRENDING_PROJECTS,
        link: "explore/trending-projects",
    },
    {
        id: "new-arrivals",
        title: "New Arrivals",
        subtitle: "Development Update",
        badge: "NEWS",
        image: STATIC_ASSETS.CAROUSEL.NEW_ARRIVALS,
        link: "/magazine/new-arrivals",
    },
    {
        id: "3d-store",
        title: "3D Store",
        subtitle: "Development Update",
        badge: "NEWS",
        image: STATIC_ASSETS.CAROUSEL.STORE_3D,
        link: "magazine/3d-store",
    },
    {
        id: "project-ideas",
        title: "Project Ideas",
        subtitle: "Development Update",
        badge: "NEWS",
        image: STATIC_ASSETS.CAROUSEL.PROJECT_IDEAS,
        link: "magazine/project-ideas",
    },
    {
        id: "scheduled-projects-2",
        title: "Scheduled Projects",
        subtitle: "Development Update",
        badge: "NEWS",
        image: STATIC_ASSETS.CAROUSEL.SCHEDULED_PROJECTS,
        link: "magazine/new-arrivals",
    },
    {
        id: "trending-projects-2",
        title: "Trending Projects",
        subtitle: "Discover the Art of Assassin's Creed Shadows",
        badge: "ART BLAST",
        image: STATIC_ASSETS.CAROUSEL.TRENDING_PROJECTS,
        link: "explore/trending-projects",
    },
];
