export const featuredMockData = [
    {
        id: "spring-sale",
        title: "Spring Sale",
        subtitle: "Shop up to 70% off",
        badge: "MARKETPLACE",
        image: "/public/assets/carousel-images/SpringSale.png",
        link: "/marketplace/featured",
    },
    {
        id: "scheduled-projects",
        title: "Scheduled Projects",
        subtitle: "Development Update",
        badge: "NEWS",
        image: "/public/assets/carousel-images/ScheduledProjects.png",
        link: "magazine/new-arrivals",
    },
    {
        id: "trending-projects",
        title: "Trending Projects",
        subtitle: "Discover the Art of Assassin's Creed Shadows",
        badge: "ART BLAST",
        image: "/public/assets/carousel-images/TrendingProjects.png",
        link: "explore/trending-projects",
    },

    {
        id: "new-arrivals",
        title: "New Arrivals",
        subtitle: "Development Update",
        badge: "NEWS",
        image: "/public/assets/carousel-images/NewArrivals.png",
        link: "/magazine/new-arrivals",
    },
    {
        id: "3d-store",
        title: "3D Store",
        subtitle: "Development Update",
        badge: "NEWS",
        image: "/public/assets/carousel-images/3d-store.png",
        link: "magazine/3d-store",
    },
    {
        id: "project-ideas",
        title: "Project Ideas",
        subtitle: "Development Update",
        badge: "NEWS",
        image: "/public/assets/carousel-images/ProjectIdeas.png",
        link: "magazine/project-ideas",
    },
    {
        id: "scheduled-projects",
        title: "Scheduled Projects",
        subtitle: "Development Update",
        badge: "NEWS",
        image: "/public/assets/carousel-images/ScheduledProjects.png",
        link: "magazine/new-arrivals",
    },
    {
        id: "trending-projects",
        title: "Trending Projects",
        subtitle: "Discover the Art of Assassin's Creed Shadows",
        badge: "ART BLAST",
        image: "/public/assets/carousel-images/TrendingProjects.png",
        link: "explore/trending-projects",
    },
];
